### ISSUE TITLE
Cannot create any bill in a project without currency

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#785]
- create a project with no currency
- add participants
- try to add a bill: it fails with:

```
Currency: Not a valid choice
```

I suspect that the form contains an actual currency, even though it isn't shown in the UI.

I'm surprised that the tests don't catch this kind of big issue...

**Comment by Glandos** [comment]
Sorry to flood issues with videos but I don't have any errors:


https://user-images.githubusercontent.com/297578/125038031-35113080-e095-11eb-982e-ebc56c36a476.mp4

I tested it with the current master, new virtualenv, new database.

**Comment by zorun** [comment]
Ok, I can only reproduce with WTForms==2.2.1 (what I had in my old virtualenv), it works fine when upgrading to 2.3.3

I think the issue is that the default currency in the "Add bill" form is wrong: when I try to add a bill on a project with currencies, the "Add bill" form shows "AED" as currency by default (the first choice in the list). I think this wrong default value explains the error I am getting on a project without currency (the form doesn't show this field, but there is still a server-side default value)

I'll just check that we would indeed catch this problem in the tests, update the requirement for WTForms, and close it then.

**Comment by zorun** [comment]
Ok, tests fail as expected (with sometimes hard-to-understand errors, but it's minor):

```
api_test.py::APITestCase::test_bills - AssertionError: 201 != 400 :  expected 201, got 400
api_test.py::APITestCase::test_bills_with_calculation - AssertionError: 201 != 400 :  expected 201, got 400
api_test.py::APITestCase::test_statistics - AssertionError: Lists differ: [{'balance': 12.5, 'member': {'activated': T[190 chars]2.5}] != [{'member': {'id': 1, 'name': 'zorglub', 'we[1...
api_test.py::APITestCase::test_weighted_bills - TypeError: string indices must be integers
budget_test.py::BudgetTestCase::test_access_other_projects - AssertionError: 0 != 1
budget_test.py::BudgetTestCase::test_export - TypeError: send_file() got an unexpected keyword argument 'download_name'
budget_test.py::BudgetTestCase::test_manage_bills - sqlalchemy.orm.exc.NoResultFound: No row was found for one()
budget_test.py::BudgetTestCase::test_membership - AssertionError: 1 != 2
budget_test.py::BudgetTestCase::test_person_model - AssertionError: False is not true
budget_test.py::BudgetTestCase::test_rounding - AssertionError: 0 != 8.12
budget_test.py::BudgetTestCase::test_statistics - AssertionError: Regex didn't match: '<td class=\\"d-md-none\\">zorglub</td>\\s+<td>\\$20\\.00</td>\\s+<td>\\$31\\.67</td>' not found i...
budget_test.py::BudgetTestCase::test_weighted_balance - AssertionError: Items in the first set but not the second:
history_test.py::HistoryTestCase::test_bill_add_remove_add - AssertionError: 3 != 5
history_test.py::HistoryTestCase::test_clear_ip_records - sqlalchemy.orm.exc.NoResultFound: No row was found for one()
history_test.py::HistoryTestCase::test_disable_clear_no_new_records - sqlalchemy.orm.exc.NoResultFound: No row was found for one()
history_test.py::HistoryTestCase::test_double_bill_double_person_edit_second - AssertionError: 3 != 5
history_test.py::HistoryTestCase::test_logs_for_common_actions - AssertionError: 'Bill <em class="font-italic">fromage à raclette</em> added' not found
```

**Comment by zorun** [comment]
This seems to be caused by #768

In general, when updating a dependency in setup.cfg, it's better to also raise the minimum version, so that existing virtualenvs get updated.
